use 'id -un' instead of USER env var (#48)
Linuxbrew/install pull request #49
Opened 2019-02-07 22:20 UTC by andreineculau

Should fix #48 but it's a blind "sed" PR.
PS: I opted for `id -un` instead of `whoami`, just to keep it in sync with the already existing group variable `id -gn`

2019-02-08 01:02 UTC, sjackman commented
Thanks for this work, Andrei! I suggest adding…
```ruby
ENV["USER"] = `id -un`.chomp unless ENV["USER"]
```

2019-02-08 01:02 UTC, sjackman requested changes
Thanks for this work, Andrei! I suggest adding…
```ruby
ENV["USER"] = `id -un`.chomp unless ENV["USER"]
```

2019-02-11 09:59 UTC, andreineculau commented
Could I ask why? as I don't see anything changing (no matter if you really mean "add", as in keep my changes and also add a ENV.USER default, or you mean "instead" of my changes, I could have just given a default value, and let almost everything else as it was)

2019-02-12 00:45 UTC, sjackman commented
Sorry I wasn't clear. Yes I meant the latter, use a default and leave everything else as is.

2019-02-12 12:18 UTC, andreineculau commented
You surely have your reasons to request that, but messing up with the env is entirely against my practices. I'm leaving my PR as is since there isn't anything wrong with it, and you can accept it or not. Thanks for linuxbrew!

2019-02-12 18:45 UTC, sjackman commented
> You surely have your reasons to request that, but messing up with the env is entirely against my practices.

The change to `ENV` is local to this install script. As soon as the script exits, the environment will be back to the way it is.

> I'm leaving my PR as is since there isn't anything wrong with it, and you can accept it or not. Thanks for linuxbrew!

Thank you for your effort.

2019-02-12 18:45 UTC, closed without merging