install.sh: install-ruby if current version > 2.6 or < 2.6
Linuxbrew/install pull request #80
Opened 2020-01-30 20:59 UTC by dawidd6

2020-01-30 22:13 UTC, sjackman approved these changes

2020-02-25 17:10 UTC, dawidd6 commented
@sjackman Is this mergeable?

2020-02-25 18:00 UTC, sjackman requested changes

2020-02-25 18:00 UTC, sjackman commented on install.sh
> +   ruby -e 'version = RUBY_VERSION.split(".").first(2).join(".").to_f; exit (version < 2.6 || version > 2.6)'; then
```suggestion
   ruby -e 'exit RUBY_VERSION.split(".").first(2).join(".") != "2.6"'; then
```

2020-02-25 18:03 UTC, sjackman approved these changes

2020-03-04 19:19 UTC, closed without merging

2020-03-04 20:23 UTC, sjackman commented
`install.sh` in Homebrew/install now supports Linux.